### PR TITLE
FEATURE/US-1/PRODUCTS PAGE

### PR DESCRIPTION
**Pull request by denisgandel**
### What?
I added a page where the user can visualize all the products available in the database, through the connection to the database and a paging system.

### How?
I used NextJS to create the page and the necessary components, besides giving it a clean design and adaptable to any device.

### Why?
Because it was necessary that the user, when entering the page, should visualize the products.

NOTE: The favorite's section is not available

Author: @denisgandel 
Reviewer: @Elvis-Castro-H 
Tester: @Misax148

### CODE REVIEW

**Review by Elvis-Castro-H — APPROVED** [review]
Good job

**Comment by Misax148** [comment]
The search engine cannot be used in any option when the window reaches the minimum size.
image

It is not possible to interact with the search engine.
image

**Comment by Misax148** [comment]
As an improvement, you could consider keeping the same position of the heart icon, price, color, shopping cart and that they do not depend or move or modify by the text description of the product.
image

**Comment by Misax148** [comment]
When I favorite the heart icon of a product on one page, the icon of another product appears as auto-selected on the next page.

Clickeando en el icono corazon - Pagina 1
image

Moving on to Page 2
image

**Comment by Misax148** [comment]
When I click as a favorite on the heart icon of products on a page, and I go to the last page, and then go back to the page where I had clicked on the heart icon of my favorite products, these products will no longer be marked as favorites, i.e. they will be unchecked when going to the last page.

Marking products as favorites on the page 1.
image

Going to the last page.
image

Back to page 1 where my favorite products were marked.
image

**Comment by denisgandel** [comment]
> When I click as a favorite on the heart icon of products on a page, and I go to the last page, and then go back to the page where I had clicked on the heart icon of my favorite products, these products will no longer be marked as favorites, i.e. they will be unchecked when going to the last page.
> 
> Marking products as favorites on the page 1. image
> 
> Going to the last page. image
> 
> Back to page 1 where my favorite products were marked. image

The part of the selection of favorites, is not permanent because it is necessary to implement the database to save all the favorite items selected by a user, this functionality will be added in the future.

**Comment by Misax148** [comment]
Image of a product is not rendered and cannot be displayed on the las page.
image

**Comment by denisgandel** [comment]
> Image of a product is not rendered and cannot be displayed on the las page. image

This part, it is an error from the database, because the image does not exists

**Comment by denisgandel** [comment]
> > Image of a product is not rendered and cannot be displayed on the las page. image
> 
This part, it is an error from the database, because the image is not exists

**Comment by denisgandel** [comment]
> The search engine cannot be used in any option when the window reaches the minimum size. image
> 
> It is not possible to interact with the search engine. image

Yes, this is because is necessary fix the design of nav bar, that this error is other US

**Comment by Misax148** [comment]
> > When I click as a favorite on the heart icon of products on a page, and I go to the last page, and then go back to the page where I had clicked on the heart icon of my favorite products, these products will no longer be marked as favorites, i.e. they will be unchecked when going to the last page.
> > Marking products as favorites on the page 1. image
> > Going to the last page. image
> > Back to page 1 where my favorite products were marked. image
> 
> The part of the selection of favorites, is not permanent because it is necessary to implement the database to save all the favorite items selected by a user, this functionality will be added in the future.

It is necessary to mention it in the description of your PR to avoid the observation.

**Comment by Misax148** [comment]
> > The search engine cannot be used in any option when the window reaches the minimum size. image
> > It is not possible to interact with the search engine. image
> 
> Yes, this is because is necessary fix the design of nav bar, that this error is other US

Thanks for the clarification, this will be a fix for the next sprint and testing should be improved! 😊

**Comment by Misax148** [comment]
> > > Image of a product is not rendered and cannot be displayed on the las page. image
> 
> This part, it is an error from the database, because the image is not exists

You must contact the DB manager to fix this problem, it cannot be uploaded to production showing that or try to fix it yourself!

**Review by Misax148 — APPROVED** [review]

**Pull request merged**
