### PR TITLE
Feature/us 48/wish list

### PR DESCRIPTION
**Pull request by Elvis-Castro-H**
## What?
- Added and removed from wishlist to database
- Implementation of the wishlist page
- Wishlist access validation only for logged in users

## Why?
- To allow users to have their wish list to add or remove products they like

## How?
- Performing queries with the Restful API

### Code review 
@Karvlox 

### Test
@saletG08

### CODE REVIEW

**Review by victor-villca — CHANGES_REQUESTED** [review]
The following bugs were found:
* For a moment before loading the complete whishlist page, only the title and the white background is shown, try to show a loading text
* The wishlit does not save the products marked as favorites.
[Screencast from 2023-11-27 19-00-42.webm](https://github.com/Les-Jailes/Boutique_Clothing/assets/101595370/9f82627f-53e1-4549-8274-ffd664a8a144)

**Comment by Elvis-Castro-H** [comment]
@victor-villca  The observations were resolved in the last commit

**Review by Karvlox — APPROVED** [review]

**Comment by saletG08** [comment]
When entering the page the title of Your Wishlist should not be displayed, only the loading screen should be displayed, correct that and make sure it is not too far to the side.

Screenshot from 2023-11-28 19-08-28

**Comment by saletG08** [comment]
At the time of adding it was seen that two products were added, that should not happen just adding one product.

Screenshot from 2023-11-28 19-09-37

**Comment by Elvis-Castro-H** [comment]
@saletG08  The fixes were added in the last commit

**Comment by saletG08** [comment]
Since there are no more products, the button should no longer appear since there is no other product page, it should not be visible, change that.

Screenshot from 2023-11-28 19-40-50

**Comment by Elvis-Castro-H** [comment]
@saletG08 Corrections were made in the last commit

**Review by saletG08 — APPROVED** [review]
Good job

**Review by victor-villca — APPROVED** [review]
Approved. I like it.

**Pull request merged**
