### PR TITLE
Feature/us 13/cart page UI creation

### PR DESCRIPTION
**Pull request by denisgandel**
NOTE: This is only an implementation of the UI and not the complete functionality and the fields doesn't have validations

CODE REVIEW: @saletG08 
TESTER: @Elvis-Castro-H

### CODE REVIEW

**Review by Elvis-Castro-H — CHANGES_REQUESTED** [review]
## Merge Conflicts
Resolve conflicts before testing

**Review by saletG08 — APPROVED** [review]
I don't have comments

**Review by Elvis-Castro-H — CHANGES_REQUESTED** [review]
## Test Report 
### Bug Found
image
On a mobile device the "checkout" option is not always available to the user

**Review by Elvis-Castro-H — APPROVED** [review]
Good job

**Pull request merged**
