### PR TITLE
Feature/us 7/UI navbar and routing

### PR DESCRIPTION
**Pull request by victor-villca**
**What did you do?**
I added the navigation bar UI and submenu implementation. This includes the creation of responsive design to ensure a smooth user experience across various devices. Additionally, I implemented navigation routing for the application.

**How did you do it?**
I used Next.js to create the navigation bar components and routes, ensuring seamless navigation within the application. The responsive design was achieved through CSS media queries and adjustments to the layout.

**Why did you do it?**
This change is essential to enhance the user experience by providing a clear and efficient navigation system. It also improves the application's usability on different devices, accommodating a wider user base.

**Author:** @victor-villca 
**Reviewer:** @saletG08 
**Tester:** @denisgandel

### CODE REVIEW

**Comment by saletG08** [comment]
There is an error in the console and in the navigation when going to the More about us page where the following image appears.  Correct it.
Screenshot from 2023-10-31 15-16-14

**Comment by victor-villca** [comment]
> There is an error in the console and in the navigation when going to the More about us page where the following image appears. Correct it. Screenshot from 2023-10-31 15-16-14

THIS ISSUE WAS ALREADY SOLVED IN THE LATEST COMMIT: https://github.com/Les-Jailes/Boutique_Clothing/pull/1/commits/ec9d2a1f85f9ed5a909e002a630aa92625985a80

**Comment by saletG08** [comment]
The CSS you have is not being used or you forgot to call it for your page, please call it if you are going to use it and if you are not going to use it then delete it.

**Comment by saletG08** [comment]
Change the logo.png image with a transparent background to make it look better.

**Review by saletG08 — APPROVED** [review]
I have no more comments, good job

**Comment by denisgandel** [comment]
I was testing the header, and it has the following errors:
1.- The categories section has some padding on the left and right sides.
2.- The logo can not be visualized in a good way, besides it seems to be too big, which does not look very good.
3.- The icons are images so I would suggest you to use the react-icons library that brings several free and easy to use icons.
4.- I would suggest that the part of the categories is not so big, it would be good that you reduce it a little, as well as the search bar.
5 .- Also something that is very bad, is that as the icons are images these can be draggeables and looks very good, since the user does not have the need to copy or drag our icons.
6 .- It is not responsive, at the time of resizing it is deleted or completely hides the search bar.
7 .- It would also be good not to be a popup menu and convert it to a side menu, so that in this way when adapted for mobile, the options of the categories are within the menu and not end up bothering at the top.

**Review by denisgandel — APPROVED** [review]

**Comment by victor-villca** [comment]
> I was testing the header, and it has the following errors: 1.- The categories section has some padding on the left and right sides. 2.- The logo can not be visualized in a good way, besides it seems to be too big, which does not look very good. 3.- The icons are images so I would suggest you to use the react-icons library that brings several free and easy to use icons. 4.- I would suggest that the part of the categories is not so big, it would be good that you reduce it a little, as well as the search bar. 5 .- Also something that is very bad, is that as the icons are images these can be draggeables and looks very good, since the user does not have the need to copy or drag our icons. 6 .- It is not responsive, at the time of resizing it is deleted or completely hides the search bar. 7 .- It would also be good not to be a popup menu and convert it to a side menu, so that in this way when adapted for mobile, the options of the categories are within the menu and not end up bothering at the top.

All observations made were solved with the latest commit: https://github.com/Les-Jailes/Boutique_Clothing/pull/1/commits/044ef625940ef39033322c719dff28eba33844a7

**Pull request merged**
