### PR TITLE
login responsiveness on box width fix

### PR DESCRIPTION
**Pull request by victor-villca**
This is the fix for the bug: https://app.clickup.com/t/8686eujgv

### CODE REVIEW

**Comment by Elvis-Castro-H** [comment]
Task linked: [CU-8686eujgv [BUG] ID - 13 Login interface overlaps navigation bar](https://app.clickup.com/t/8686eujgv)

**Comment by saletG08** [comment]
When I put the form on the mobile mode screen, the form appears this way, there are some buttons that are not visible, they are only visible on a larger screen, fix that.

Screenshot from 2023-11-27 23-33-51

Screenshot from 2023-11-27 23-34-11

**Comment by saletG08** [comment]
Resolve your Merge Conflict

**Comment by victor-villca** [comment]
> Resolve your Merge Conflict

Solved: 
image

**Comment by saletG08** [comment]
Screenshot from 2023-11-29 19-45-27

validations are superimposed on the button

**Review by saletG08 — APPROVED** [review]
Good Job

**Review by Misax148 — APPROVED** [review]

**Pull request merged**
