### PR TITLE
Feature/us cu 8686hh8vv/id   50   contact us page

### PR DESCRIPTION
**Pull request by victor-villca**
#### What did I do?

Implemented the Contact Us page to allow users to easily contact the company for inquiries or support. This enhancement aims to improve the overall user experience and ensure seamless communication.

#### Why did I do it?

As a user visiting our website, the ability to contact the company easily is crucial for inquiries or support. This feature enhances user experience and ensures that users can reach out effortlessly through a dedicated Contact Us page.

#### How did I do it?

1. **Routing and Navigation:**
   - Created a new route and instant redirection.

2. **Responsive Design:**
   - Applied CSS media queries for responsiveness.

3. **Form Implementation:**
   - Designed a user-friendly form with validation.

4. **Client-Side Validation:**
   - Implemented JavaScript for instant feedback.

Author: @victor-villca 
Tester: @Misax148 
Reviewer: @Karvlox

### CODE REVIEW

**Comment by Elvis-Castro-H** [comment]
Task linked: [CU-8686hh8vv ID - 50 - Contact us page](https://app.clickup.com/t/8686hh8vv)

**Review by Karvlox — APPROVED** [review]
Good job.

**Comment by Misax148** [comment]
The user can add numbers in Name section

image

**Comment by Misax148** [comment]
The user can add letters on Telephone section.

image

**Comment by Misax148** [comment]
I can make a request with fields that have bad parameters. Ex: Name and Telephone.
image

**Review by Misax148 — APPROVED** [review]
Good job!

**Pull request merged**
