### PR TITLE
Feature/us 22/header UI fix

### PR DESCRIPTION
**Pull request by denisgandel**
## WHAT?
Perform a refactoring of the Header or Nav Bar

## HOW?
By changing some sections of the Nav Bar

## WHY?
Because the Header had different problems in the Responsive part, the access to different pages within the application

> AUTHOR: @denisgandel 
> CODE REVIEWER: @Misax148 
> TESTER: @Elvis-Castro-H

### CODE REVIEW

**Review by Elvis-Castro-H — APPROVED** [review]
Everything ok. Good job.

**Review by Elvis-Castro-H — CHANGES_REQUESTED** [review]
Some messages are printed to the console, if this was part of the development process, it is no longer necessary during program execution
image
image

**Review by Elvis-Castro-H — APPROVED** [review]
Everything ok. Good job.

**Review by Misax148 — APPROVED** [review]
No observations, great job!

**Pull request merged**
