### PR TITLE
Feature/us 19/user profile page

### PR DESCRIPTION
**Pull request by Karvlox**
## What have I done?
User interface for user-profile
so that the user can view his account details

## How did I do it?
I designed the user interface of the user-profile form using React components.
I implemented css for a good window layout.

## Why did I do this?
So that users can see their account details on the website.

**Author:** @Karvlox 
**Reviewer:** @Elvis-Castro-H 
**Tester:** @Misax148

### CODE REVIEW

**Comment by Misax148** [comment]
Aligns the Gender text and fixes the Gender expansion symbol:

image

**Review by Elvis-Castro-H — APPROVED** [review]
Everything ok

**Comment by Misax148** [comment]
When I reduce the screen to less than 800 wide, some elements of the user profile become cluttered or not responsive.

image

**Comment by Misax148** [comment]
When I reduce the screen to less than 600 widths, all the forms return to their position except the last one, the last one grows in width as its size is further reduced.
image

**Review by Misax148 — APPROVED** [review]

**Pull request merged**
