### PR TITLE
Feature/us 30/about us UI

### PR DESCRIPTION
**Pull request by victor-villca**
**What did I do?**
In this pull request, I implemented the "About Us" UI feature, as outlined in User Story ID 30. I created a dedicated section following the provided mockup, ensuring it clearly identifies and presents information about the site's history, development team, values, philosophy, corporate culture, and future vision.

**Why did I do it?**
The goal was to enhance user experience by offering a comprehensive overview of the site. This includes not only its background and history but also insights into the people behind it, the core values, and the future vision. By providing this information in a clear and concise manner, we aim to engage users and create a more meaningful connection with the site.

**How did I do it?**
To achieve this, I structured the "About Us" section to align with the provided mockup. I ensured the wording is clear, concise, and accessible to a broad spectrum of users. Additionally, I made the page responsive for mobile devices, optimizing the user experience across different screen sizes.

**Author:** @victor-villca 
**Code-Reviewer:** @Elvis-Castro-H 
**Tester:** @Misax148

### CODE REVIEW

**Review by Elvis-Castro-H — APPROVED** [review]
Everything ok. Good job.

**Comment by Misax148** [comment]
Improve the background image quality please!

image

**Comment by Misax148** [comment]
The arrow options to rotate the images are not visible at 100% size for the browser.
image

You must zoom out to be able to interact with them.
image

**Review by Misax148 — APPROVED** [review]
Good job!

**Pull request merged**
