### PR TITLE
Feature/us 10/modify items in the cart

### PR DESCRIPTION
**Pull request by denisgandel**
>> AUTHOR: @denisgandel 
>> CODE REVIEWER: @victor-villca 
>> TESTER: @saletG08

### CODE REVIEW

**Comment by saletG08** [comment]
In the YOUR CART view within the products, when you want to increase how many products of the same you want and edit the input trying to delete it, it is set to 1, which I have to perform the delete action twice and it is not very efficient, correct so that it can be edited by pressing the delete keyboard just once and entering the number of the quantity of products you want to buy.

Related Video
[recording-2023-11-14-19-45-03.webm](https://github.com/Les-Jailes/Boutique_Clothing/assets/135137641/8b2a1225-de44-49d7-8226-249a4b930c98)

**Comment by saletG08** [comment]
delete it from the console

Screenshot from 2023-11-15 08-26-55

**Comment by saletG08** [comment]
resolve conflicts

**Review by victor-villca — APPROVED** [review]
The functionality works. Approved

**Review by saletG08 — APPROVED** [review]
I don't have any comments

**Pull request merged**
