### PR TITLE
Feature/US-42/Payment Validation Handler

### PR DESCRIPTION
**Pull request by Misax148**
**What did I do?**
- I implemented error messages for different payment failure scenarios.
- I added route validations for empty cart, incomplete form and user authentication.
- I updated the database schema to include the details of the products that were purchased during the purchase.
- I added the update of the quantity of the products that are being purchased in the DB.

**How did I do it?**
- Using a swal.fire to show the notification of the different cases of card validation.
- Using a toast and useEffects to detect certain parameters.
- Saving the purchased products in the DB. 
- Updating the number of products available in the database after making the purchase.

**Why did I do it?**
- So that the user cannot directly access the route without having certain form criteria filled out.
- So that in the future the history of paid products is implemented.
- So that the user knows the number of products available in our inventory.

**TESTING CONSIDERATIONS & NOTES**

**Routes validations**: 
- If the user enters directly to the `/pages/checkout/payment` route and is not logged in, they must be redirected to the Login `/pages/account/login`, displaying a message that they must be logged in before making a purchase in a `Toast`.
- If the user enters directly to the `/pages/checkout/payment` route and if they are logged in, but do not have a single product added to the cart, they must be redirected to `/pages/products` showing a message that they must add products if they want to make a purchase in a `Toast`.
- If the user enters directly to the `/pages/checkout/payment` route and if they are logged in, and if they have added products, but have not filled out the previous checkout form, they must be redirected to `/pages/checkout`, showing a message that they must fill out the data in a `Toast`.

**Card payment validation**
For this test you can try the following valid credit cards:
- Visa: `4242 4242 4242 4242` | Any 3 digits | Any future Date | `12345` ex zip code
- Visa (Debit): `4000 0566 5566 5556` | Any 3 digits | Any future Date | `12345` ex zip code
- Mastercard: `5555 5555 5555 4444` | Any 3 digits | Any future Date | `12345` ex zip code
- American Express: `3782 822463 10005` | Any 3 digits | Any future Date | `12345` ex zip code
- Discover: `6011 1111 1111 1117` | Any 3 digits | Any future Date | `12345` ex zip code
- Union Pay: `6200 0000 0000 0005` | Any 3 digits | Any future Date | `12345` ex zip code

There are different types of validations that were added, some examples to take as an example for the test are:
- If you press the 'Buy' button without having entered any data on the card, an error message will appear saying that the card number is incomplete.
- If you enter all the card information correctly, except for the date, that is, a date past the current date, you will receive an error regarding the expired card.
- If you enter the number of the invalid card and press 'Buy', an error will appear informing you that the card is not valid.
- If you want to test some more specific scenarios you can test the following:
    - Generic decline | `4000 0000 0000 0002` | Any 3 digits | Any future Date | `12345` ex zip code
    - Insufficient funds decline	| `4000 0000 0000 9995` | Any 3 digits | Any future Date | `12345` ex zip code
    - Stolen card decline | `4000 0000 0000 9979` | Any 3 digits | Any future Date | `12345` ex zip code
    - Expired card decline	| `4000 0000 0000 0069` | Any 3 digits | Any future Date | `12345` ex zip code.
    - Incorrect CVC decline | `4000 0000 0000 0127` | Any 3 digits | Any future Date | `12345` ex zip code.
    - Processing error decline | `4000 0000 0000 0119` | Any 3 digits | Any future Date | `12345` ex zip code.
 
**Quantity stock updating**:
If you want to know if the quantity of products is updating after a purchase, you can do the following:
- Access the following link: https://boutique-clothing-api.onrender.com/Product
- Search for a product you want to try, for example:
    - code: 128
    - sizes array position 0: size -> "XS"": quantity: 5
- In the UI add that product and buy 3 units of that size.
- Once the purchase is made, return to the API-REST and verify that the quantity decreased.
- **ADDITIONALLY**: In this section the only validation that exists is that the quantity is not less than 0. This is because the validation of available stock will be carried out in US: 38.

**Author:** @Misax148 
**Reviewer:** @Karvlox  
**Test**: @denisgandel  

**Link | Click Up | US:42 :** https://sharing.clickup.com/9011140495/t/h/8686fkytm/WCM6RXY2A9ME458

### CODE REVIEW

**Review by Karvlox — APPROVED** [review]
Good job.

**Review by Elvis-Castro-H — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by denisgandel — APPROVED** [review]
Good job :smile:

**Review by Elvis-Castro-H — APPROVED** [review]
Good job.

**Pull request merged**
